### ISSUE TITLE
Errors Adobe AIR and FlashPlayer with autopkg 1.4.2

### ISSUE THREAD

**Issue by mikemazurkiewicz** [autopkg/filewave#21]
We use autopkg for Adobe products with FileWave. We have started to recieve these errors this morning and cannot figure out what is causing them.

Any help would be appreciated.

MikeM.

The following failures occurred:

RECIPE
com.github.autopkg.filewave.FlashPlayerNoRepackage	

MESSAGE
Error in com.github.autopkg.filewave.FlashPlayerNoRepackage: Processor: URLDownloader: Error: Curl failure: The requested URL returned error: 404 Not Found (exit code 22)

The following errors occurred:

WARNING: com.github.autopkg.filewave.AdobeAIR is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding... WARNING: com.github.autopkg.filewave.FlashPlayerNoRepackage is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding... Curl failure: The requested URL returned error: 404 Not Found (exit code 22)

**Comment by gregneagle** [comment]
About the warnings: it looks like you recently updated to AutoPkg 1.0 or 1.0.1. A major new feature is support for recipe trust.

See https://github.com/autopkg/autopkg/wiki/AutoPkg-and-recipe-parent-trust-info for more info.

Note that these are _warnings_. You can choose to ignore them if you'd like.

As for your 404 error, you should run the recipe with higher verbosity (-v or -vv), take note of the URL and try it yourself in a browser...

**Comment by mikemazurkiewicz** [comment]
Today it ran without a problem, so I will have to believe a downstream server may have been having problem. Both Air and FlashPlayer are packaging correctly.

Thanks,
MikeM.
