### ISSUE TITLE
Error: too many values to unpack

### ISSUE THREAD

**Issue by mikemazurkiewicz** [autopkg/filewave#27]
Hello,
We recently upgraded to FileWave 12.7.0 and have been getting consistent errors from AutoPkgr. I have confirmed that the user can still log into FW Admin. The command-line produces the same error.

sd95mdm1:Applications techsysadmin$ autopkg run FWTool.filewave
Processing FWTool.filewave...
WARNING: FWTool.filewave is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
Path to Admin Tool: /Applications/FileWave/FileWave Admin.app/Contents/MacOS/FileWave Admin
too many values to unpack
Failed.

The following recipes failed:
    FWTool.filewave
        Error in com.github.autopkg.filewave.FWTool: Processor: com.github.autopkg.filewave.FWTool/FWTool: Error: too many values to unpack

Nothing downloaded, packaged or imported.

Is there a problem with the FWTool, or something specific with our installation?

**Comment by pierrenicolasr** [comment]
https://github.com/autopkg/filewave/pull/29 should fix this issue - Qt library has been updated with 12.7.0 and it outputs more warnings than in 12.3-.

**Comment by mikemazurkiewicz** [comment]
Reinstalling the updated version seems to have fixed our problem.
Thanks
