### ISSUE TITLE
Unexpected contents

### ISSUE THREAD

**Issue by jfuchtm** [autopkg/filewave#37]
Seeing the following on FW recipes.
Processor com.github.autopkg.filewave.FWTool/FileWaveImporter contents differ from expected. Path: /Users/ladmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.filewave/FWTool/FileWaveImporter.py

**Comment by homebysix** [comment]
This is an expected result of recipe override trust info needing an update. Please check out the AutoPkg wiki page here: https://github.com/autopkg/autopkg/wiki/AutoPkg-and-recipe-parent-trust-info
