### ISSUE TITLE
Filewave Recipes don't allow overriding the group in their current form

### ISSUE THREAD

**Issue by tempusthales** [autopkg/filewave#6]
FileWave recipes don't allow you to override the group in their current form.  This would allow us to change the group where the filesets get uploaded to into the server.  It would be ideal for this to be allowed, so that recipes can use %fw_fileset_group% in the actual FWImporter arguments. (For Example: https://macadmins.slack.com/files/elliotjordan/F0MQX0G3G/evernote.xml)

The end result would be two fold:
1. Change the group where a fileset is imported via an override 
   a. Right click on a FileWave recipe, choose Create Override.
   b. Then edit the file as you would any recipe override, save.
   c. Set AutoPkgr to run the override, not its parent.
2. FileWaveImporter tool should read the group from a defaults setting, so you could set it once and forget it.
   a. AutoPkgr could write that setting, based on a field in the UI.

**Comment by johncclayton** [comment]
Fixed - README.md updated - please try the latest version that was pushed yesterday and let me know if this works for you.
